### ISSUE TITLE
Online version deployed using GitHub Page

### ISSUE THREAD

**Issue by iamchristianani** [iamchristianani/portfolio#10]
I was able to deploy my website online by making use of GitHub Page.

Below is the link to my portfolio hosted on GitHub: 
[Visit Website](https://iamchristianani.github.io/portfolio/)

or copy out the link here

https://iamchristianani.github.io/portfolio/

**Comment by leonardodiasb** [comment]
# Status: ✔️ Project Approved ✔️ 

Hi @iamchristianani,

Everything is looking great! Please, merge this branch :shipit:
Congratulations! 🎉

## Highlights

 -  Professional README. ✔️

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
